image: maven:3-openjdk-8

include:
  - template: Code-Quality.gitlab-ci.yml

stages:
  - build
  - test
  - package
  - code_quality

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  FF_NETWORK_PER_BUILD: "true"
  # FF_NETWORK_PER_BUILD - Coloca tudo na mesma rede. Os services e o container onde roda a build.

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - mvn clean compile -Dcheckstyle.skip

test:
  services:
    - name: selenium/standalone-chrome
      alias: selenium-chrome-browser
  stage: test
  script:
    - SPRING_PROFILES_ACTIVE=test mvn test
  artifacts:
    when: always
    untracked: false
    expire_in: 30 days
    reports:
      junit: target/surefire-reports/TEST-*.xml
    paths:
      - target/surefire-reports
      - target/site/jacoco
      - target/checkstyle-result.xml
      - target/*.png

package:
  stage: package
  script:
    - SPRING_PROFILES_ACTIVE=release mvn package -Dmaven.test.skip=true
  artifacts:
    untracked: false
    expire_in: 30 days
    paths:
      - target/*.jar

code_quality:
  stage: code_quality
  artifacts:
    expose_as: 'Code Quality Report'
    paths: [gl-code-quality-report.json]
