image: maven:3-openjdk-8

stages:
  - build
  - test
  - package

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  FF_NETWORK_PER_BUILD: "true"
  # FF_NETWORK_PER_BUILD - Coloca tudo na mesma rede. Os services e o container onde roda a build.

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - SPRING_PROFILES_ACTIVE=dev mvn clean compile -Dcheckstyle.skip

test:
  services:
    - name: selenium/standalone-chrome
      alias: selenium-chrome-browser
  stage: test
  script:
    - SPRING_PROFILES_ACTIVE=dev mvn test
  artifacts:
    when: always
    untracked: false
    expire_in: 30 days
    paths:
      - target/surefire-reports
      - target/checkstyle-result.xml
      - target/*.png

package:
  stage: package
  script:
    - mvn package -Dmaven.test.skip=true
  artifacts:
    untracked: false
    expire_in: 30 days
    paths:
      - target/*.jar
