
image: maven:3.6.3

pipelines:
  default:
    - step:
        name: Build and Test
        caches:
          - maven
        script:
          - mvn -B package
        artifacts:
          - target/*.jar
          - target/surefire-reports/*.txt
        after-script:
          - pipe: atlassian/checkstyle-report:0.2.0
